<?php

namespace AppBundle\Repository;

use AppBundle\Document\Channel;
use AppBundle\Document\Scene;
use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * SceneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SceneRepository extends DocumentRepository
{
    /**
     * @param $sceneId
     * @param Channel $channel
     * @return Scene
     */
    public function getSceneByIdInChannel($sceneId,$channel){
        return $this->findOneBy([
            'id' => $sceneId,
            'channel.id' => $channel ? $channel->id : ''
        ]);
    }
}