/* Generated By:JavaCC: Do not edit this line. InvariantParserTreeConstants.java Version 5.0 */
package invariant.invariantEvaluator.Parser;

public interface InvariantParserTreeConstants
{
  public int JJTINV_EXP = 0;
  public int JJTOREXPR = 1;
  public int JJTOREXPR_ = 2;
  public int JJTANDEXPR = 3;
  public int JJTANDEXPR_ = 4;
  public int JJTATOMINV = 5;
  public int JJTRANGE = 6;
  public int JJTSET = 7;
  public int JJTVARDECL = 8;
  public int JJTARITM = 9;
  public int JJTSUMEXPR = 10;
  public int JJTSUMEXPR_ = 11;
  public int JJTMULTEXPR = 12;
  public int JJTMULTEXPR_ = 13;
  public int JJTATOM = 14;


  public String[] jjtNodeName = {
    "Inv_exp",
    "OrExpr",
    "OrExpr_",
    "AndExpr",
    "AndExpr_",
    "atomInv",
    "Range",
    "Set",
    "VarDecl",
    "Aritm",
    "SumExpr",
    "SumExpr_",
    "multExpr",
    "multExpr_",
    "atom",
  };
}
/* JavaCC - OriginalChecksum=fe61bbbb85a9fc76d72595c3b033000e (do not edit this line) */
